// Copyright 2025 DigitalKin Inc.
//
// Licensed under the GNU General Public License, Version 3.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.gnu.org/licenses/gpl-3.0.html
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

syntax = "proto3";

package digitalkin.cost.v1;

import "buf/validate/validate.proto";

// CostType: Enum for the type of cost
enum CostType {
    // OTHER: Other type of cost
    OTHER = 0;
    // TOKEN_INPUT: Token input cost
    TOKEN_INPUT = 1;
    // TOKEN_OUTPUT: Token output cost
    TOKEN_OUTPUT = 2;
    // API_CALL: API call cost
    API_CALL = 3;
    // STORAGE: Storage cost
    STORAGE = 4;
    // TIME: Time cost
    TIME = 5;
}

// Cost: Message to represent a cost
message Cost {
    // cost: The cost value
    double cost = 1 [(buf.validate.field).required = true];
    // mission_id: Mission ID linked to the cost
    string mission_id = 2 [(buf.validate.field).required = true, (buf.validate.field).string.prefix = "missions:"];
    // name: Name of the cost
    string name = 3 [(buf.validate.field).required = true];
    // cost_type: Type of the cost
    CostType cost_type = 4 [(buf.validate.field).required = true];
    // unit: Unit of the cost
    string unit = 5 [(buf.validate.field).required = true];
    // rate: Rate of the cost
    double rate = 6 [(buf.validate.field).required = true];
    // setup_version_id: Setup version ID linked to the cost
    string setup_version_id = 7 [(buf.validate.field).required = true, (buf.validate.field).string.prefix = "setup_versions:"];
    // quantity: Quantity of the cost
    double quantity = 8 [(buf.validate.field).required = true];
}

// AddCostRequest: Request to add a cost
message AddCostRequest {
    // cost: The cost value
    double cost = 1 [(buf.validate.field).required = true];
    // mission_id: Mission ID linked to the cost
    string mission_id = 2 [(buf.validate.field).required = true, (buf.validate.field).string.prefix = "missions:"];
    // name: Name of the cost
    string name = 3 [(buf.validate.field).required = true];
    // cost_type: Type of the cost
    CostType cost_type = 4 [(buf.validate.field).required = true];
    // unit: Unit of the cost
    string unit = 5 [(buf.validate.field).required = true];
    // rate: Rate of the cost
    double rate = 6 [(buf.validate.field).required = true];
    // setup_version_id: Setup version ID linked to the cost
    string setup_version_id = 7 [(buf.validate.field).required = true, (buf.validate.field).string.prefix = "setup_versions:"];
    // quantity: Quantity of the cost
    double quantity = 8 [(buf.validate.field).required = true];
}

// AddCostResponse: Response to added cost
message AddCostResponse {
}


// CostFilter: Filter criteria for costs
message CostFilter {
    // names: Filter costs by one or more names
    repeated string names = 1;
    
    // cost_types: Filter costs by cost types
    repeated CostType cost_types = 2;
}

// GetCostsRequest: Request to get multiple costs
message GetCostsRequest {
    // mission_id: Mission ID linked to the cost
    string mission_id = 1 [(buf.validate.field).required = true, (buf.validate.field).string.prefix = "missions:"];
    // filter: Filter criteria for costs
    CostFilter filter = 2;
}

// GetCostsResponse: Response to get multiple costs
message GetCostsResponse {
    // costs: List of cost
    repeated Cost costs = 1 [(buf.validate.field).required = true];
}

// GetCostRequest: Request to get cost by name
message GetCostRequest {
    // mission_id: Mission ID linked to the cost
    string mission_id = 1 [(buf.validate.field).required = true, (buf.validate.field).string.prefix = "missions:"];
    // name: Name of the cost
    string name = 2 [(buf.validate.field).required = true];
}

// GetCostResponse: Response to get cost by name
message GetCostResponse {
    // costs: List of cost
    repeated Cost costs = 1 [(buf.validate.field).required = true];
}
